trigger:
  - main

pr:
  autoCancel: true

# GCC
stages:
- stage: GCC
  dependsOn: []
  variables:
  - name: CC
    value: gcc
  - name: CXX
    value: g++
  jobs:
  - template: ./pipelines/jobs-linux.yml
    parameters:
      jobName: 'Validate GCC'
      imageName: ubuntu-latest

# Clang
- stage: Clang
  dependsOn: []
  variables:
  - name: CC
    value: clang
  - name: CXX
    value: clang++
  jobs:
  - template: ./pipelines/jobs-linux.yml
    parameters:
      jobName: 'Validate Clang'
      imageName: ubuntu-latest

# Apple-Clang
- stage: Apple_Clang
  dependsOn: []
  jobs:
  - template: ./pipelines/jobs-macos.yml
    parameters:
      jobName: 'Validate Apple-Clang latest'
      imageName: macos-latest
