parameters:
  jobName: ''
  imageName: ''

jobs:
- job:
  displayName: ${{ parameters.imageName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  strategy:
    matrix:
      debug:
        BUILD_TYPE: 'Debug'
      release:
        BUILD_TYPE: 'Release'
  continueOnError: false

  steps:
  - script: 'pip install wget'
    displayName: 'Install wget'

  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: |
        import wget
     
        print('Beginning file download with wget module')
        url = "https://sourceforge.net/projects/openblas/files/v0.3.7/OpenBLAS-0.3.7-x64.zip"
        path = r"$(Build.ArtifactStagingDirectory)"
        wget.download(url, path)

  - powershell: |
      mkdir openblas
      Expand-Archive OpenBLas-0.3.7-x64.zip -DestinationPath .\openblas
      $env:BLAS_DIR=Get-Location
      $env:PATH="$env:BLAS_DIR\bin;$env:PATH" 
    name: Prepare

  - task: CMake@1
    name: Configure
    inputs:
      workingDirectory: build
      cmakeArgs: ' -DBUILD_BENCH=OFF .. '

  - task: CMake@1
    name: Build
    inputs:
      workingDirectory: build
      cmakeArgs: '--build . --config $(BUILD_TYPE)'

  - script: ctest -C $(BUILD_TYPE) --output-on-failure --no-compress-output
    name: CTest
    workingDirectory: build
    failOnStderr: true
