parameters:
  jobName: ''
  imageName: ''

jobs:
- job:
  displayName: ${{ parameters.imageName }} pool:
    vmImage: ${{ parameters.imageName }}
  strategy:
    matrix:
      debug:
        BUILD_TYPE: 'Debug'
      release:
        BUILD_TYPE: 'Release'
  continueOnError: false

  steps:
  - powershell: |
      $env:BLAS_DIR = ${Build.SourcesDirectory}\openblas
      mkdir $env:BLAS_DIR
      nuget install OpenBLAS -o $env:BLAS_DIR
      $env:BLAS_ROOT=$env:BLAS_DIR\OpenBLAS.0.2.14.1\lib\native
      $env:PATH="$env:BLAS_ROOT\win32\bin;$env:BLAS_DIR\native\x64\bin;$env:PATH"
    name: Prepare

  - task: CMake@1
    name: Configure
    inputs:
      workingDirectory: build
      cmakeArgs: ' -DBUILD_BENCH=OFF .. '

  - task: CMake@1
    name: Build
    inputs:
      workingDirectory: build
      cmakeArgs: '--build . --config $(BUILD_TYPE)'

  - script: ctest -C $(BUILD_TYPE) --output-on-failure --no-compress-output
    name: CTest
    workingDirectory: build
    failOnStderr: true
