parameters:
  jobName: ''
  imageName: ''

jobs:
- job:
  displayName: ${{ parameters.imageName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  strategy:
    matrix:
      debug:
        BUILD_TYPE: 'Debug'
      release:
        BUILD_TYPE: 'Release'
  continueOnError: false

  steps:
  - powershell: |
      nuget install OpenBLAS -o "."
      $env:BLAS_DIR=Get-Location
      $env:PATH="$env:BLAS_DIR\OpenBLAS.0.2.14.1\lib\native\win32\bin;$env:BLAS_DIR\OpenBLAS.0.2.14.1\lib\native\x64\bin;$env:PATH" 
    name: Prepare

  - task: CMake@1
    name: Configure
    inputs:
      workingDirectory: build
      cmakeArgs: ' -DBLAS_DIR="./OpenBLAS.0.2.14.1/lib/native" -DBUILD_BENCH=OFF .. '

  - task: CMake@1
    name: Build
    inputs:
      workingDirectory: build
      cmakeArgs: '--build . --config $(BUILD_TYPE)'

  - script: ctest -C $(BUILD_TYPE) --output-on-failure --no-compress-output
    name: CTest
    workingDirectory: build
    failOnStderr: true
