name: Codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-linux:
    strategy:
      matrix:
        compiler: [g++-13]
    runs-on: ubuntu-24.04

    steps:
    - name: Build stdBLAS
      run: |
        git clone https://github.com/stigrs/stdBLAS.git
        cd stdBLAS
        mkdir build
        cd build
        cmake .. -DLINALG_ENABLE_TESTS=OFF -DLINALG_ENABLE_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}} 
        cmake --build . --config ${{env.BUILD_TYPE}}
        sudo cmake --install . 
    
    - uses: actions/checkout@v3

    - name: Prepare
      # Install necessary software
      run: |
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
          | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install intel-oneapi-mkl-devel-2025.2 lcov
      
    - name: Configure CMake
      run: |
        source /opt/intel/oneapi/setvars.sh intel64
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DScilib_BUILD_BENCH=OFF

    - name: Build
      run: |
        source /opt/intel/oneapi/setvars.sh intel64
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        source /opt/intel/oneapi/setvars.sh intel64
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      
    - name: Code coverage
      working-directory: ${{github.workspace}}/build
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' "${{github.workspace}}"'/build/_deps/*' "${{github.workspace}}"'/tests/*' -o coverage-info
        lcov --list coverage.info
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov
